=== Inter-Trust/Aspect_Generation/source code/1stMilestone-demo3_opensource/xmlSchemas/securityAspectualKnowledge/SAK_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema targetNamespace="http://inter-trust.eu/schema/interpreter/sds" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sds="http://inter-trust.eu/schema/interpreter/sds">
    <xsd:complexType name="sds">
        <xsd:annotation>
            <xsd:documentation>Security Deployment Specification</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="deploy" minOccurs="0" />
            <xsd:element name="undeploy" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="category">
        <xsd:sequence>
            <xsd:element name="securityConcept" type="sds:securityConcept" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:anyURI" use="required" />
    </xsd:complexType>
    <xsd:complexType name="securityConcept">
        <xsd:sequence>
        	<xsd:element name="target" type="sds:target" minOccurs="0" />
        	<xsd:element name="functionality" type="sds:functionality"
        		maxOccurs="unbounded" minOccurs="0" />
        	<xsd:element name="configuration" type="sds:configuration"
        		minOccurs="0" />
        	<xsd:element name="candidateAspect"
        		type="sds:candidateAspect" minOccurs="0" maxOccurs="unbounded">
        	</xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required" />
        <xsd:attribute name="type" type="xsd:anyURI" />
    </xsd:complexType>
    <xsd:complexType name="target">
        <xsd:attribute name="id" type="xsd:anyURI" use="required" />
    </xsd:complexType>
    <xsd:complexType name="functionality">
        <xsd:attribute name="id" type="xsd:anyURI" use="required" />
    </xsd:complexType>
    <xsd:complexType name="configuration">
        <xsd:choice>
            <xsd:element name="securityParameters" type="sds:securityParameters" />
            <xsd:element name="securityDescription" type="xsd:anyType" />
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="securityParameters">
        <xsd:sequence>
            <xsd:element name="parameter" type="sds:securityParameter" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="securityParameter">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="deploy">
        <xsd:sequence>
        	<xsd:element name="category" type="sds:category"
        		minOccurs="0" maxOccurs="unbounded" />
        	<xsd:element name="aspect" type="sds:aspect" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="undeploy">
        <xsd:sequence>
        	<xsd:element name="undeploySecurityConcept" minOccurs="0" maxOccurs="unbounded">
        		<xsd:complexType>
        			<xsd:attribute name="id" type="xsd:string" />
        		</xsd:complexType>
        	</xsd:element>
        	<xsd:element name="aspect" type="sds:aspect" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="sds" type="sds:sds" />

    <xsd:element name="listAF" type="sds:listAF"></xsd:element>
    
    <xsd:complexType name="listAF">
    	<xsd:sequence>
    		<xsd:element name="aspect" type="sds:aspect" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="aspect">
    	<xsd:sequence>
    		<xsd:element name="advice" type="sds:advice" minOccurs="0"
    			maxOccurs="unbounded">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="advice">
    	<xsd:sequence>
    		<xsd:element name="functionality" type="sds:functionality"
    			minOccurs="1" maxOccurs="unbounded">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

    <xsd:element name="adaptationPlan" type="sds:adaptationPlan"></xsd:element>
    
    <xsd:complexType name="adaptationPlan">
    	<xsd:sequence>
    		<xsd:element name="deploy" type="sds:deploy"></xsd:element>
    		<xsd:element name="undeploy" type="sds:undeploy"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="mappingSCA" type="sds:mappingSCA"></xsd:element>
    
    <xsd:complexType name="mappingSCA">
    	<xsd:sequence>
    		<xsd:element name="securityConcept"
    			type="sds:securityConcept" minOccurs="0" maxOccurs="unbounded">
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="candidateAspect">
    	<xsd:sequence>
    		<xsd:element name="aspect" type="sds:aspect" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Inter-Trust/Aspect_Generation/source code/1stMilestone-demo3_opensource/clientFiles/listAspectFunctionalityClient.xml
<?xml version="1.0" encoding="UTF-8"?>
<sds:listAF xmlns:sds="http://inter-trust.eu/schema/interpreter/sds" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://inter-trust.eu/schema/interpreter/sds SAK_Schema.xsd ">

<sds:aspect id="1" name="evoting.aspects.client.Authentication_UserPassword_EVotingClient">
    <sds:advice id="1" name="authenticate">
      <sds:functionality id="http://inter-trust.eu/security/authentication#userpass-authentication"/>
    </sds:advice>
  </sds:aspect>
  <sds:aspect id="2" name="evoting.aspects.client.Authentication_X509certificate_EVotingClient">
  	<sds:advice id="1" name="authenticate">
  		<sds:functionality id="http://inter-trust.eu/security/authentication#certificate-authentication"/>
  		<sds:functionality id="http://inter-trust.eu/security/authentication#x509certificate"/>
  	</sds:advice></sds:aspect>
  <sds:aspect id="3" name="evoting.aspects.client.Encryption_DSA_EVotingClient">
  	<sds:advice id="1" name="encryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
  		<sds:functionality id="http://inter-trust.eu/security/secure-message-format#pkcs7"/>
  	</sds:advice>
  	<sds:advice id="2" name="decryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#decryption"/>
  		<sds:functionality id="http://inter-trust.eu/security/secure-message-format#pkcs7"/>
  	</sds:advice>
  </sds:aspect>
  <sds:aspect id="4" name="evoting.aspects.client.Encryption_RSA_EVotingClient">
  	<sds:advice id="1" name="encryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
  		</sds:advice>
  	<sds:advice id="2" name="decryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
  		</sds:advice>
  		</sds:aspect>
  <sds:aspect id="5" name="evoting.aspects.client.ElapsedTimeMonitoring_EVotingClient">
  	<sds:advice id="1" name="time">
  		<sds:functionality id="http://inter-trust.eu/monitoring/timing#executiontime"/>
  	</sds:advice>
	</sds:aspect>
	  <sds:aspect id="6" name="evoting.aspects.client.Encryption_AES_Client">
  	<sds:advice id="1" name="encryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
  		<sds:functionality id="http://inter-trust.eu/security/secure-message-format#pkcs5"/>
  	</sds:advice>
  	<sds:advice id="2" name="decryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#decryption"/>
  		<sds:functionality id="http://inter-trust.eu/security/secure-message-format#pkcs5"/>
  	</sds:advice>
  </sds:aspect>
</sds:listAF>

=== Inter-Trust/Aspect_Generation/source code/1stMilestone-demo3_opensource/serverFiles/listAspectFunctionalityServer.xml
<?xml version="1.0" encoding="UTF-8"?>
<sds:listAF xmlns:sds="http://inter-trust.eu/schema/interpreter/sds" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://inter-trust.eu/schema/interpreter/sds SAK_Schema.xsd ">

<sds:aspect id="1" name="evoting.aspects.server.Authentication_UserPassword_EVotingServer">
    <sds:advice id="1" name="authenticate">
      <sds:functionality id="http://inter-trust.eu/security/authentication#userpass-authentication"/>
    </sds:advice>
  </sds:aspect>
  <sds:aspect id="2" name="evoting.aspects.server.Authentication_X509certificate_EVotingServer">
  	<sds:advice id="1" name="authenticate">
  		<sds:functionality id="http://inter-trust.eu/security/authentication#certificate-authentication"/>
  		<sds:functionality id="http://inter-trust.eu/security/authentication#x509certificate"/>
  	</sds:advice></sds:aspect>
  <sds:aspect id="3" name="evoting.aspects.server.Encryption_DSA_EVotingServer">
  	<sds:advice id="1" name="encryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
  		<sds:functionality id="http://inter-trust.eu/security/secure-message-format#pkcs7"/>
  	</sds:advice>
  	<sds:advice id="2" name="decryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#decryption"/>
  		<sds:functionality id="http://inter-trust.eu/security/secure-message-format#pkcs7"/>
  	</sds:advice>
  </sds:aspect>
  <sds:aspect id="4" name="evoting.aspects.server.Encryption_RSA_EVotingServer">
  	<sds:advice id="1" name="encryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
  		</sds:advice>
  	<sds:advice id="2" name="decryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
  		</sds:advice>
  		</sds:aspect>
  <sds:aspect id="5" name="evoting.aspects.server.ElapsedTimeMonitoring_EVotingServer">
  	<sds:advice id="1" name="time">
  		<sds:functionality id="http://inter-trust.eu/monitoring/timing#executiontime"/>
  	</sds:advice>
	</sds:aspect>
	  <sds:aspect id="6" name="evoting.aspects.server.Encryption_AES_Server">
  	<sds:advice id="1" name="encryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
  		<sds:functionality id="http://inter-trust.eu/security/secure-message-format#pkcs5"/>
  	</sds:advice>
  	<sds:advice id="2" name="decryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#decryption"/>
  		<sds:functionality id="http://inter-trust.eu/security/secure-message-format#pkcs5"/>
  	</sds:advice>
  </sds:aspect>
</sds:listAF>

=== Inter-Trust/Aspect_Generation/source code/1stMilestone-demo3_opensource/xmlSchemas/securityAspectualKnowledge/listAspectFunctionality.xml
<?xml version="1.0" encoding="UTF-8"?>
<sds:listAF xmlns:sds="http://inter-trust.eu/schema/interpreter/sds" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://inter-trust.eu/schema/interpreter/sds SAK_Schema.xsd ">

<sds:aspect id="1" name="Authentication_UserPassword">
    <sds:advice id="1" name="authenticate">
      <sds:functionality id="http://inter-trust.eu/security/authentication#userpass-authentication"/>
    </sds:advice>
  </sds:aspect>
  <sds:aspect id="2" name="Authentication_X509certificate">
  	<sds:advice id="1" name="authenticate">
  		<sds:functionality id="http://inter-trust.eu/security/authentication#certificate-authentication"/>
  		<sds:functionality id="http://inter-trust.eu/security/authentication#x509certificate"/>
  	</sds:advice></sds:aspect>
  <sds:aspect id="3" name="Encryption_DSA">
  	<sds:advice id="1" name="encryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
  		<sds:functionality id="http://inter-trust.eu/security/secure-message-format#pkcs7"/>
  	</sds:advice>
  	<sds:advice id="2" name="decryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#decryption"/>
  		<sds:functionality id="http://inter-trust.eu/security/secure-message-format#pkcs7"/>
  	</sds:advice>
  </sds:aspect>
  <sds:aspect id="4" name="Encryption_RSA">
  	<sds:advice id="1" name="encryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
  		</sds:advice>
  	<sds:advice id="2" name="decryption">
  		<sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
  		</sds:advice>
  		</sds:aspect>
  <sds:aspect id="5" name="ElapsedTimeMonitorization">
  	<sds:advice id="1" name="time">
  		<sds:functionality id="http://inter-trust.eu/monitorization/timing#executiontime"/>
  	</sds:advice>
	</sds:aspect>
</sds:listAF>
