=== Inter-Trust/Aspect_Generation/SecurityDeploymentSpecification/target/classes/SDS.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://inter-trust.eu/schema/interpreter/sds"
    xmlns:sds="http://inter-trust.eu/schema/interpreter/sds"
    elementFormDefault="qualified">
    <xsd:complexType name="sds">
        <xsd:annotation>
            <xsd:documentation>Security Deployment Specification</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="deploy" minOccurs="0" type="sds:deploy"/>
            <xsd:element name="undeploy" minOccurs="0" type="sds:undeploy"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="category">
        <xsd:sequence>
            <xsd:element name="securityFeature" type="sds:securityFeature" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:anyURI" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="securityFeature">
        <xsd:sequence>
            <xsd:element name="target" type="sds:target" minOccurs="1"/>
            <xsd:element name="functionality" type="sds:functionality" maxOccurs="unbounded" minOccurs="0"/>
            <xsd:element name="configuration" type="sds:configuration" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:anyURI"/>
    </xsd:complexType>
    <xsd:complexType name="target">
        <xsd:attribute name="id" type="xsd:anyURI" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="functionality">
        <xsd:attribute name="id" type="xsd:anyURI" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="configuration">
        <xsd:choice>
            <xsd:element name="securityParameters" type="sds:securityParameters"/>
            <xsd:element name="securityDescription" type="xsd:anyType"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="securityParameters">
        <xsd:sequence>
            <xsd:element name="parameter" type="sds:securityParameter" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="securityParameter">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="deploy">
        <xsd:sequence>
            <xsd:element name="category" type="sds:category" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="undeploy">
        <xsd:sequence>
            <xsd:element name="undeploySecurityFeature" type="sds:undeploySecurityFeature" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="undeploySecurityFeature">
        <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
    <xsd:element name="sds" type="sds:sds"/>
</xsd:schema>

=== Inter-Trust/Aspect_Generation/SDSProducer/files/SDSexampleConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<sds:sds xmlns:sds="http://inter-trust.eu/schema/interpreter/sds" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://inter-trust.eu/schema/interpreter/sds SDS.xsd ">
  <sds:deploy>
   <sds:category id="Authentication2">
      <sds:securityFeature id="2" type="Authentication">
        <sds:target id="authenticationPoints"/>
        <sds:functionality id="Authentication#example"/>
        <sds:configuration>
          <sds:securityParameters>
            <sds:parameter name="protected-item">StationId</sds:parameter>
            <sds:parameter name="pseudonym">cert-field:stationId</sds:parameter>
          </sds:securityParameters>
        </sds:configuration>
      </sds:securityFeature>
    </sds:category>
    
    <sds:category id="Authentication">
      <sds:securityFeature id="1" type="Authentication">
        <sds:target id="authenticationPoints"/>
        <sds:functionality id="Authentication#certificate"/>
        <sds:configuration>
          <sds:securityParameters>
            <sds:parameter name="CU">UMU</sds:parameter>
            <sds:parameter name="key-type">X509</sds:parameter>
            <sds:parameter name="hashing">sha1</sds:parameter>
            <sds:parameter name="fomat">etsi</sds:parameter>
            <sds:parameter name="key">Pseudonym</sds:parameter>
            <sds:parameter name="algorithm">DSA</sds:parameter>
          </sds:securityParameters>
        </sds:configuration>
      </sds:securityFeature>
    </sds:category>
  </sds:deploy>
  <sds:undeploy>
  </sds:undeploy>
  <sds:instance id="user001"/>
</sds:sds>

=== Inter-Trust/Aspect_Generation/SDSProducer/files/SDSexampleTest2.xml
<?xml version="1.0" encoding="UTF-8"?>
<sds:sds xmlns:sds="http://inter-trust.eu/schema/interpreter/sds" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://inter-trust.eu/schema/interpreter/sds SDS.xsd ">
  <sds:deploy>
    <sds:category id="Authentication">
      <sds:securityFeature id="1" type="Authentication">
        <sds:target id="authenticationPoints"/>
        <sds:functionality id="Authentication#certificate"/>
        <sds:configuration>
          <sds:securityParameters>
            <sds:parameter name="CU">UMA</sds:parameter>
          </sds:securityParameters>
        </sds:configuration>
      </sds:securityFeature>
    </sds:category>
  </sds:deploy>
  <sds:undeploy>
  </sds:undeploy>
  <sds:instance id="user001"/>
</sds:sds>

=== Inter-Trust/Aspect_Generation/SDSProducer/files/SDSexampleSpringAOP.xml
<?xml version="1.0" encoding="UTF-8"?>
<sds:sds xmlns:sds="http://inter-trust.eu/schema/interpreter/sds" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://inter-trust.eu/schema/interpreter/sds SDS.xsd ">
  <sds:deploy>
    <sds:category id="VR">
      <sds:securityFeature id="10" type="VR">
        <sds:target id="Vote"/>
        <sds:functionality id="voterejection"/>
        <sds:configuration>
        </sds:configuration>
      </sds:securityFeature>
    </sds:category>
  </sds:deploy>
  <sds:undeploy>
  </sds:undeploy>
  <sds:instance id="user001"/>
</sds:sds>

=== Inter-Trust/Aspect_Generation/executable_demonstrator/EVotingClient/clientFiles/escenario1Client.xml
<?xml version="1.0" encoding="UTF-8"?>

<sds:sds xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:sds='http://inter-trust.eu/schema/interpreter/sds'
   xsi:schemaLocation='http://inter-trust.eu/schema/interpreter/sds SDS.xsd'>
    <sds:deploy>
        <sds:category id="http://inter-trust.eu/security/access-control">
            <sds:securityConcept id="2" type="http://inter-trust.eu/security/authentication">
                <sds:target id="http://inter-trust.eu/csa/vehicle/authnmodule"/>
                <sds:functionality id="http://inter-trust.eu/security/authentication#certificate-authentication"/>
                <sds:functionality id="http://inter-trust.eu/security/authentication#x509certificate"/>
                <sds:configuration>
                    <sds:securityParameters>
                        <sds:parameter name="CA">C=ES, O=DIRECCIÓN GENERAL DE TRÁFICO, OU=ITS, CN=DGT.GOB.ES</sds:parameter>
                    </sds:securityParameters>
                </sds:configuration>
            </sds:securityConcept>
        </sds:category>
        <sds:category id="http://inter-trust.eu/security/cryptography">
            <sds:securityConcept id="3" type="http://inter-trust.eu/security/encryption">
                <sds:target id="http://inter-trust.eu/csa/vehicle/cam-sender"/>
                <sds:functionality id="http://inter-trust.eu/security/confidentiality#encryption"/>
                <sds:functionality id="http://inter-trust.eu/security/secure-message-format#pkcs7"/>
                <sds:configuration>
                    <sds:securityParameters>
                        <sds:parameter name="Algorithm">DSA</sds:parameter>
                    </sds:securityParameters>
                </sds:configuration>
            </sds:securityConcept>
        </sds:category>
        <sds:category id="http://inter-trust.eu/security/monitoring">
            <sds:securityConcept id="7" type="http://inter-trust.eu/security/timing">
                <sds:target id="http://inter-trust.eu/csa/vehicle/cam-sender"/>
                <sds:functionality id="http://inter-trust.eu/monitoring/timing#executiontime"/>
            </sds:securityConcept>
        </sds:category>
    </sds:deploy>
    <sds:undeploy>
    </sds:undeploy>
</sds:sds>
